server:
  port: 9090
project:
  dir:
    conf: /Users/sailor/git/spring-cloud-demo/scd-conf-server/src/main/resources
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${project.dir.conf}/conf/xx
          version: 1.9.42000
        git:
          uri: file:///Users/sailor/git/config
      label: mop

